[package]
name = "KaiLeverage"
license = "Apache 2.0"
authors = ["Krešimir Klas (kklas@kunalabs.io)"]
edition = "2024.beta"
published-at = "0xe6079b606e2c6ea73511f1c22f31c2312e3610a3916908174b415147a37040d8"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.35.2", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.35.2", override = true }
AccessManagement = { local = "../../../access-management" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "mainnet-v1.23.1" }
TurbosCLMM = { git = "https://github.com/turbos-finance/turbos-sui-move-interface.git", subdir = "clmm", rev = "8887603" }
FlowxClmm = { local = "../../../_vendor/FlowxClmm" }
Pyth = { local = "../../../_vendor/Pyth" }
WHUSDCE = { local = "../../../_vendor/whUSDCe" }
WHUSDTE = { local = "../../../_vendor/whUSDTe" }
usdc = { local = "../../../_vendor/USDC/usdc" }
BluefinSpot = { git = "https://github.com/fireflyprotocol/bluefin-spot-contract-interface.git", subdir = "", rev = "5dfcb03" }
SuiUsdt = { local = "../../../_vendor/SuiUsdt" }
USDY = { local = "../../../_vendor/USDY" }

[addresses]
kai_leverage = "0x51e0ccce48f0763f98f1cb4856847c2e1531adacada99cdd7626ab999db57523"
